version: "3.8"
services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - the-everything-shop
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 2s
      retries: 20

  backend:
    build: ./backend
    image: the-everything-shop-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - ${BE_PORT}:${BE_PORT}
    environment:
      AUTH_SECRET: ${AUTH_SECRET}
      AUTH_SECRET_EXPIRES_IN: ${AUTH_SECRET_EXPIRES_IN}
      AUTH_REFRESH_SECRET: ${AUTH_REFRESH_SECRET}
      AUTH_REFRESH_SECRET_EXPIRES_IN: ${AUTH_REFRESH_SECRET_EXPIRES_IN}
    depends_on:
      - db
    networks:
      - the-everything-shop

  frontend:
    build: ./frontend
    image: the-everything-shop-frontend
    restart: unless-stopped
    ports:
      - ${FE_PORT}:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - the-everything-shop

  prisma-studio:
    image: node:alpine
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app
    command: npx prisma studio --port 5555 --browser none
    ports:
      - $PRISMA_STUDIO_PORT:5555
    env_file:
      - ./backend/.env
    networks:
      - the-everything-shop
    depends_on:
      - db
      - backend

networks:
  the-everything-shop:
