services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - the-everything-shop
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 2s
      retries: 20
    # command: postgres -c listen_addresses='*'

  app:
    build: .
    image: the-everything-shop-backend
    restart: unless-stopped
    env_file: .env
    ports:
      - ${APP_PORT}:${APP_PORT}
      # - ${APP_HOST}:${APP_HOST}
    environment:
      AUTH_SECRET: ${AUTH_SECRET}
      AUTH_SECRET_EXPIRES_IN: ${AUTH_SECRET_EXPIRES_IN}
      AUTH_REFRESH_SECRET: ${AUTH_REFRESH_SECRET}
      AUTH_REFRESH_SECRET_EXPIRES_IN: ${AUTH_REFRESH_SECRET_EXPIRES_IN}
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
      - ./.env:/app/.env
      - ./tsconfig.json:/app/tsconfig.json
    depends_on:
      - db
    networks:
      - the-everything-shop

  prisma-studio:
    image: node:alpine
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: npx prisma studio --port 5555 --browser none
    ports:
      - "5555:5555"
    env_file:
      - .env
    networks:
      - the-everything-shop
    depends_on:
      - db
      - app

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - the-everything-shop

networks:
  the-everything-shop:
