services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - tes-dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 2s
      retries: 20
    # command: postgres -c listen_addresses='*'

  app:
    build: .
    image: the-everything-shop-backend
    restart: unless-stopped
    env_file: .env
    ports:
      - ${APP_PORT}:${APP_PORT}
      # - ${APP_HOST}:${APP_HOST}
    environment:
      AUTH_SECRET: ${AUTH_SECRET}
      AUTH_SECRET_EXPIRES_IN: ${AUTH_SECRET_EXPIRES_IN}
      AUTH_REFRESH_SECRET: ${AUTH_REFRESH_SECRET}
      AUTH_REFRESH_SECRET_EXPIRES_IN: ${AUTH_REFRESH_SECRET_EXPIRES_IN}
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
      - ./.env:/app/.env
      - ./tsconfig.json:/app/tsconfig.json
    depends_on:
      - db
      - s3
    networks:
      - tes-dev

  prisma-studio:
    image: node:alpine
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: npx prisma studio --port 5555 --browser none
    ports:
      - "5555:5555"
    env_file:
      - .env
    networks:
      - tes-dev
    depends_on:
      - db
      - app

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - tes-dev

---
services:
  s3:
    image: minio/minio
    container_name: s3
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=adminpass
    networks:
      - tes-dev
    volumes:
      - ./.data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
  mc:
    image: minio/mc
    container_name: mc
    depends_on:
      - s3
    networks:
      - tes-dev
    entrypoint: >
      sh -c "
      sleep 3 &&
      /usr/bin/mc alias set tess3 http://s3:9000 admin adminpass &&
      /usr/bin/mc mb tess3/tes &&
      exit 0
      "

networks:
  tes-dev:
    name: tes-dev
