name: Docker CI pipeline

on:
  # push:
  #   branches:
  #     # - main 
  #     # - devel
  #     # - hotfix/*
  #     # - fix/**/*
  pull_request:
    branches:
      - main
      - devel
      - feat/*
      # - hotfix/*
  workflow_dispatch:

jobs:
  docker-build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up environment
        run: |
          cat .env
          source .env

      - name: Install dependencies
        run:
          npm ci

      - name: Eslint (backend)
        run: |
          npx eslint ./src

      - name: Run Docker compose (backend)
        run: |
          docker compose up -d --build

      - name: Test Api health
        run: |
          source .env
          for i in {1..10}; do
            if curl -f http://localhost:${APP_PORT}/api/health > /dev/null; then
              echo "Backend is up!"
              exit 0
            fi
            echo "Waiting backend..."
            sleep 3
          done
          echo "Backend failed to start"
          docker compose logs
          docker compose down
          exit 1

      - name: Stop containers
        if: always()
        run: docker compose down
